<?php
/**
 * @file
 * amv_base.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function amv_base_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Chunibyo & Other Delusions',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '000d2c81-e905-4717-9b6c-5685566cb933',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Melancholy of Haruhi Suzumiya Season 1 and 2',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0095287a-595b-4f8b-b91b-b8cb6b118769',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kampfer (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '00c43a94-9d00-4524-b192-b69b569775e6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ah My Goddess!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '015e8889-24a2-454f-8532-79eec87d6257',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nichijou',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '01f023ac-e26a-4d08-a213-92a90ddd6c2a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Monogatari Series: First Season',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '032370c4-79ce-4b77-bb17-f823b1cd9c43',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kotoura-san',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '03b70fb6-9ef2-449a-bde3-2a527f8e6b9e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Guilty Crown',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '03d1ab5f-6938-43e9-a08b-e7d898657d46',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Evangelion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '03e26eaf-ae93-48db-996e-f6ec992c5073',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mahou Shoujo Madoka Magica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '055d2189-83cb-4b7c-92eb-229b34abfeb1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Maji de Watashi ni Koi Shinasai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '05cecb25-46dd-4004-89e4-b35f8789b928',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Puella Magi Madoka Magica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '05f69919-0195-4f05-acb0-5b5bee86d725',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Oreimo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '067a8324-3b51-4b15-a94a-ec15f6811bc2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Highschool of the Dead',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '08198b3f-9d9a-4b88-b5f0-49873961ee81',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ore no imouto ga konna ni kawaii wake ga nai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '08dfc87e-8dd0-4c21-82b3-5a6703541803',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Yuyushiki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0a37ed36-15d4-45cf-b27d-3fca891f053f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Muella Magic Madoka',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0a6f0c90-cbda-4800-aae7-d3411b8b6e85',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Rebuild of Evangelion 1-3',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b23ad46-ab38-4202-b059-d58b3e618386',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'No Game No Life',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b978ffe-3ac1-4a31-baa4-df6146db64cf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hellsing Ultimate',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0be1f77a-7cdf-4a6a-9828-94ec9117a55c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Angel Beats',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0cc0b6b0-9778-4d3b-a175-7e00ed9a0841',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Myosis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ce9116c-ffa9-4224-9ce9-ab20c2a2f79e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'sss',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d483f55-b3ac-4c10-ab62-008d441d5602',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Golden Time',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d678f0c-82f1-41e2-a06d-4f93ed7efe20',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ore no Imouto ga Konnani Kawaii Wake ga Nai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d834202-2de4-42d9-8862-96163a16aefd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hunter x Hunter (2011)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ddf5d5b-1cc9-40ed-acbc-a707658b4515',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Black Rock Shooter OVA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0e008152-e7da-4267-9323-73d5d7db7e4d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Bunny Drop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0e2bd2fb-4b92-4049-88d5-c88cce413f24',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Golgo 13 The Professional',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0e9169ad-c791-4720-b50a-b4f1bd2a4d92',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nisemonogatari',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '103b2636-c41e-45da-a65b-0b1ed0e19128',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Amazing Nuts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '104005b8-7ddd-4aa6-aed8-d25ec35ab79c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'kaze no stigma',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10575c75-4e57-4cba-97bd-5432058bdb9b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kyoukai no Kanata',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10ba737f-54b5-4e1f-9cad-77f87b988d29',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Global Astroliner',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '117d63a9-f246-4b09-8028-c860bca714d4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mikakunin de Shinkoukei',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '11c6a435-f697-4dee-9c51-6dba909eeea7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Maoyuu Maou Yuusha',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '13d4323b-a3bd-4f8d-863e-c35f4009f386',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'sacred seven',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1457a0a5-bcac-4402-8f5b-a660d8fbcc53',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Attack on Titan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '147def33-b9fe-4983-91e0-e4379803aac7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Denpa Onna to Seishun Otoko',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1509afa0-29d9-43eb-b595-c0131a29cf18',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Chuunibyou Demo Koi ga Shitai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '150d70ad-608e-4cb8-8456-c805860e8ae1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nekomonogatari',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '158b7f89-13bf-4afa-ab95-63bc3b6da748',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Akuma No Riddle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16b53364-22e1-4e9e-99fa-52188a254bdb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ouran High School Host Club',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16ca1f78-d400-416c-b7b4-93f7b34353e5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'kobato',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '17809275-c67f-45ee-83b2-64e62a86233f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Chuunibyou demo Koi ga Shitai!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '17da774c-2493-4974-ac73-70f0657624fc',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Cosplay Complex',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '18cdcd1a-f5df-4c4a-9316-d0c8231cc9e7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ga-Rei Zero',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1988c2d7-7d3c-45ca-ab39-1ed9f79452fe',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Paprika',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '19f108b3-b190-453b-992a-5e0274b22c70',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sailor Moon (OVAs)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1a24426d-dde9-4bb6-a4f7-6170f127844f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'From up on Poppy Hill',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1a77d04f-345c-47f0-aa38-4a2524f467b0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fate Zero',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1a9469d0-bde6-4270-a511-233c9fc5dfe4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Cat Planet Cuties (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1b4ea815-5e6d-4ced-853d-74b91f1ef185',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Love Live School Idol Project!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ba5962e-6cbe-43d5-9dba-78c34f37427d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Corpse Party: Tortured Souls - Bougyaku Sareta Tamashii No Jukyou',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1c3cbcbd-6fd4-47be-9ddf-02abb89347d3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad: Another World',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1cce358a-f2e5-43ce-8843-3b45316ba97a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'dfnqzdkkbc',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1cee9c4d-e8f6-40c6-94dd-458aa8052204',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'as',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1d67a679-06e7-43ac-92f2-bf1d5c815332',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Puella Magi Madoka Magica (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1d7b5ccd-b241-4505-bbb2-e434e3327958',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Neon Genesis Evangelion: End of Evangelion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1d81b21e-12bd-4297-bdae-09fbf85a690e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'II & III',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1d883cab-904a-4506-b5e8-16e21f97c852',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '5CM Per Second',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1d99378a-e144-4e83-8503-7b26f3fb46cb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Rosario to Vampire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1dc28561-c2b1-42e2-b97a-134612943f06',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Saki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e2f8230-1b9e-40b6-8489-669dc83e7fa8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad After Story',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e4b991e-b232-4f6c-a82f-dd8c1f69b099',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e9d790b-230b-46e5-b027-2477c42fcae9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Chunibyo & Other Delusions',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ee4dfee-6063-49b4-95d5-588df1c26e1a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Rozen Maiden (2013)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1f796185-0bff-46d3-afef-9f552ee1f973',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'FateStay Night',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1fbd5a56-2935-43db-bb73-125ae791f085',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kuroko no basket',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2090342c-ba07-4cae-8916-45b5361c6ba8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toaru Majutsu no Index',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '209a153a-853a-401d-b09c-28a1c839fb75',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Pure Funk',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '20ce69f9-1c5f-4092-b04d-9bcb0f08c46c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Zero No Tsukaima F',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '210fec22-6e4b-4e01-a8ee-82af40dfa9fb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'FullMetal Alchemist Brotherhood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2126d65a-108f-472b-ad5a-dcd8663f13c4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Tatami Galaxy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '21ffe439-d8d3-4abe-ae32-52728beb2802',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hourou Musuko',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2262cc6f-4499-4524-8b77-a2776da1902a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Rebuild of evangelion 2.0',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22a0b770-d822-4e4a-a5a1-7d84bf6dcd32',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'and Durarara!!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22e93671-afb1-4bd8-8447-504cd5c8db43',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Touka Gettan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22f0ab15-444c-43be-a93d-1755eb61c48d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'mahoromatic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '22f0bba3-ba06-4a30-a253-63d3dab385f9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Idol Master Infinite Stratos',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '231d4ae7-e52d-4e04-b070-07d8673bafbf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Byōsoku Go Senchimētoru',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2349b4b1-7eba-464c-a814-12f47d564554',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Summer Wars',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '24d0ace2-9082-4972-9a5b-8788c255b3c0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Puella Magi Madoka Magica series',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2513d675-af4f-4702-a757-33c3c0eb9dec',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nazo no Kanojo X',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2559e284-3d9a-4aba-b899-907bcf5279d9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'zkkygs@vlqjgs.com',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '278c4d16-8729-4093-8be1-375a86044a0c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Jellal x Erza',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2801bc17-20e3-44b5-9e91-fd9d6ac5ed5c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mardock Scramble: The First Compression',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29223892-49a1-4d13-9e68-b2ad09926a50',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'kinect-dance central Thrilar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2927f893-ba3d-4aac-9e34-dd50a45768da',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Air Gear',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2942314b-ec6d-4d9d-8337-c0311322d14f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ayashi no Ceres',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '295a78d9-19a2-42f5-a392-05b8b3dc7783',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Akira',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '296732ff-e688-4bc5-9341-3d6af82fc8ac',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Puella Magi Madoka Magica the movie: Rebellion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '299b35f4-9fbc-4521-8112-8c0c9b118d6c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'AIR Movie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '29ed733f-f149-4a79-92c4-83ea6856dfd9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Chihayafuru',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2ab75ff7-fe67-4afa-8e6a-62deca3e9f3b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ga-Rei-Zero',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2b3d49a2-fb15-4dd1-9ed1-36080506bae3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Eden of the East',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2bc68623-8be5-45df-a02d-ee757d9b774e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Death Note',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2cb99501-7b07-4fa4-a946-360d512ae2fb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'True Tears',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2cc9fbe7-f516-4942-9215-d1c819b5d5e7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fate/Stay Night',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2f7610eb-8a6b-4bcf-ab6a-e98ebe9042e3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'AKB0048',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '300ba5ca-0ea1-4941-ae69-59b0b13fdb7a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Monogatari Series: Second Season',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30a418a0-1529-493c-bf3c-b0fe34316668',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Angel Beats!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30ee1b61-884e-41eb-8712-2e6b9025f66a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Girl that Leapt Through Time',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3156bffd-baf3-4bca-b367-3b9c14428fc8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kanon (2006)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '319ed53b-3c92-427e-aebe-a32e6d56794a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Omamori Himari (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '31bb906c-deca-4f67-9cc7-efe3fc4fcbb5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '5 centimeters per second',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '31fe63fc-80bf-43fa-a478-34334f5cecaf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hakkenden: Touhou Hakken Ibun 2',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '326dab71-010e-4206-bd9c-7cd1e538da1f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'SGT Frog',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '32c4dd29-a4cc-4fb2-b126-999c9a9dad20',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hotarubi No Mori E',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3370cd3b-bfd3-466c-b2ac-b91b7f0d50f9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Various',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33e2744b-b37f-43b8-8864-451f9e232e8a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Digimon: Our War Game',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '33ed35ac-e4de-43e7-88ed-18730808da1c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Wolf Children Ame and Yuki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '340c6616-2eea-4715-b56a-9c40d1afdacb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Princess and the Pilot',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '34c1511e-b626-4121-9861-b20f0089b75b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'asqq',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '34e634e1-9db9-4125-94a9-d32e568f5f6a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Children Who Chase Lost Voices From Deep Below',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '35308c1f-d53b-4346-921e-c2223476cba6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tokyo Ravens',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '360247c4-4d1e-4705-8417-936862018ec0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Bungaku Shoujo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '37e7730b-292f-4ebf-a179-95f76a050363',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toaru Majutsu no Index II',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '397c753a-39a4-4fd3-83e9-d7bd2047ecf6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'dfjrwhouy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '397e2227-6a62-40d8-bd88-2e8cc301d69f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tonari no Kaibutsu-kun',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3984e663-dfde-43db-b104-d19298f195cc',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shin Sekai Yori (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a5e1183-553b-4630-9de3-751635dd5978',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shuffle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b066bac-0a4e-4070-b186-14c1f542894e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Black rock shooter (Movie)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b09523d-a7d6-4108-9a19-8dd3bf009923',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Memories',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b75da99-0003-4047-8645-ab08a286af67',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b92581b-21c0-44d6-90e1-26c6c6f57baf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Soul Eater',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3bc755f2-66d5-4903-84ea-dd6a1daa0468',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Familiar Of Zero: The Rider Of The Twin Moons (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3bd46f4c-4f3b-4efd-b6ec-c490c1292d2c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sakurasou no Pet na Kanojo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3c340217-01f0-44e4-9b3f-7d2171e362b7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Baby Princess 3D Paradise Love',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3c671cce-8b0c-4f30-9caa-3a77978fbed2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ef - a tale of melodies',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3e5ed4b5-9864-4592-be16-60aac81bd03a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'My-Hime',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3efa3738-cf28-4840-b4cd-e76856f6bba8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shugo Chara Doki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3fa2b558-9c8a-4344-977e-8d6a664e681c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Vairous',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '401019f7-1e50-45b4-b2a4-e1cef64c9ee8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Say',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4095d27d-c4d3-49eb-8410-bb171df4f36b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Genius Party Beyond',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '423eaaea-fb00-481e-9e33-4d9166de5421',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tamako Market',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '42ae92c1-f880-4e08-b2fe-2fbf18f6250b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Code Geass: Lelouch of the Rebelion R2',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '42e92e1b-4564-4f98-b669-8dea27a70605',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Yondemasu yo, Azazel-san',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '431790c1-8f3b-4ffe-b45a-b218df1f01d3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Magi the Labyrinth of Magic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4335e4e8-d467-41b0-8bdb-fcdd6a3c07c6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gosick (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43e5eb5c-f791-43e8-8ff5-fd03e05cdc5a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'AKB0048 Next Stage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '476ce333-92b0-4b5a-9fb8-1038aab4bbda',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Dimension Bomb',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '47a3e0d3-e7aa-4ded-86d1-6b7025baa88a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kotonoha no Niwa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '48bb37db-b8e2-4d10-a563-363a1d3e8e31',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Chaos;Head',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '49155543-a636-4b4d-aa3a-8ff8f78e833a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kimi ni todoke',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '498b1a42-5f46-47d9-bc21-9dff9453a407',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Love Live!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '49ccc55b-6f5b-425d-b5ff-0ac600874a04',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'WATAMOTE ~ No Matter How I Look At It',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a0b8002-c98c-423c-9b26-cc1c18e70595',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '07-Ghost',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a267f34-e597-40f3-864a-20d67a83226a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Romeo X Juliet',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a3a2cc2-80e7-4f8b-9fb2-2fda850b1324',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kakumeiki Valvrave',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4adecf2b-facf-4f0c-8026-85dbf83526d7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Persona 4: The Animation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4bb36336-9e81-44a9-b3db-89b6ecfa3f33',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fortune Arterial',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4bdd9a6d-c7d4-4dec-b002-ca23ff7f3407',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Uchouten Kazoku',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4bff56f5-2e40-4ea8-afa5-6c09cd35e2ed',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Little Busters Refrain',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d0c005e-5b2e-4532-b385-be8d08ec25c1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shingeki no Kyojin/Attack on Titan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d71fa85-9155-4e2a-adc1-692f133afdaa',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kara no Kyoukai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d841b69-b949-4651-a4f9-4a9294b32094',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Please see comments. This field can not hold more then 10 names',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4ec6f326-cffc-43db-9ec1-cf642cf175c9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Pokemon Origins',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4eff44cd-553d-4f0e-8588-f1805e9bc388',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Full Metal Alchemist Brotherhood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4fd8e47b-a9f2-4409-9aca-6e133b113cb1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'This Ugly Yet Beautiful World',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '500a8071-4c52-4233-aa43-12087984a9e1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kuroko no Basuke',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '507e1820-3f74-4001-8c1f-99069eeb2858',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sora no Otoshimono',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '514d2df4-e6f7-4b53-8131-24217a36df98',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nagi no Asukara',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '51d72dd5-4aa8-4e0e-85e7-01a1f4bb76c9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Needless',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '525da3f6-c6b4-4fbd-8b39-8cfbd52c12b5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Steins Gate',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '52662b27-5869-4374-a903-a22b9216ef28',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Place Promised in Our Early Days',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '532a6218-a1ec-4c12-9dc1-cde5088e7cf9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Maria + Holic: Alive',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54541ac8-c18f-4548-aac5-197611707cec',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tasogare Otome x Amnesia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5455e67c-1b01-484d-a637-c5b7ba63beab',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shiki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5462e2ed-4eae-4cbd-8b64-45e005f89e71',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Digimon Adventure',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54cb3331-e02b-4ce1-b048-df474210be8e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Appleseed',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5561cd5d-67ee-4543-a2ec-53110c52b594',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mirai Nikki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '559ba83a-1d80-49a7-a65e-ac8e43cb4c84',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Majestic Prince',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '55c94534-9e70-4704-9010-b77818473289',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kids on the Slope',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5605b88b-624e-466e-9702-b405d6aebd50',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gokujo. Gokurakuin Joshikou Ryou Monogatari',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5747bcf4-5bd2-4422-a830-398f89f26d25',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'SoniAni',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5821069d-05b9-4520-8dd6-4a767f405444',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Boku wa Tomodachi ga Sukanai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '586c35d4-c662-4ac7-ab5c-54056b85f709',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'pandora hearts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '58f9b303-5ec2-4dcf-b404-af2b2d651f09',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'regPTLecA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59a73409-c23b-4cd1-8076-d97daaeb36d8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Non Non Biyori',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a550901-b6af-4081-b777-f6b29f783707',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Denpa Onna',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a9b3bf6-39e0-4239-85f7-c4e8338c60a9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mahou Shoujo Madoka Magica: Rebellion Story',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5ae7d07e-5903-4daf-a74e-e4faf6cd0e36',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Yosuga no Sora',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5b24bd7c-c90c-45d3-857e-446f750d6f10',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '\'Wanwa\' the Doggy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5bb84f92-2c83-4e94-a2e8-0e6a9bce9cc4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Isshuukan Friends',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5bd85de3-a34f-4d3f-a03d-dc303cf2c02c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Rebuild of Evangelion 1.0',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5c81866f-3cef-45b6-87e7-85bbb06383a0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hoshizora e Kakaru Hashi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d08e4cc-d6bf-4a4a-900e-4250fc0a82a4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sora no Otoshomono',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e0df41c-4c46-4bc0-828c-a0c74faa02e4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Suisei No Gargantia (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e46cd55-31d8-4c26-9e43-9b9a048b3e24',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Soul Eater-Repeat Show',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e7ca370-8c7f-4366-9616-d290631d3805',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Inu x Boku SS',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '603a16af-6756-452e-b712-b4a1580ab960',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Polar Bear\'s Cafe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '60d3e50b-6946-4fd1-bcf2-d005d647ac59',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kanon 2006',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6146a4d8-2089-426b-823e-26944b59f341',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Astarotte no Omocha!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '621e64d5-473e-4f3a-8fdc-fb625a01d43c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Samurai X - Trust (OVA) Act 1: The Man of the Slashing Sword',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6250c66a-ddcd-4410-8f0c-ec721b038687',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tokyo Magnitude 8.0',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '62d30c93-0544-48dd-b4fa-8361eb7d1488',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Umineko No Naku Koro Ni',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '630526c4-7c8c-4643-b3f0-da0a2d0477a9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Appleseed Ex Machina',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '63743b81-05b3-4ab0-8871-a9c792a90e0c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '11eyes (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64b9cc11-efc5-40c5-9ce3-601f2a5c1dea',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Anohana: The Flower We Saw That Day',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64c1f307-aa9e-47f1-8784-1ea32fa93e4f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sword of the Stranger',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64f5e5f6-3101-4b7d-8025-4e3f77ea9d34',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Another (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '65ea3d06-8407-4bf6-8d37-8a8804af00e1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Digimon: Diaboromon Strikes Back',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '661abf61-acdf-437f-8bc9-c873fa681389',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'busuo shinki moon angel',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '670e0994-7a3d-49aa-89a9-a84e44f68b10',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'bleach episode 1',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '672ff286-bdb0-4ab6-9a62-0253d69a27e2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sailor Moon (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '67d36eac-6136-474b-a8e0-10dd0f151f28',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tiger & Bunny',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '682e9eb5-f8fd-45ba-95c9-a73dfc0c4a95',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '686ed18e-cd47-48f4-a12c-ad6814e8dd3d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kannazuki no Miko',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '688d5b55-a0b3-4b01-9dd4-f6f7eb0a97b5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Disapearance of Haruhi Suzumiya (movie)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a2f8a91-c4f5-4e57-8c93-4ea99e41b2fe',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Uchuu Kyoudai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a3e7402-96a2-4930-bae8-9b559b27341c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hibi Chouchou (manga)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6b271583-32cc-440c-8907-83a8ba074740',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Valkyria Chronicles',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6b34ea55-75b8-4bc4-9772-d5dfd54d7b31',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Familiar Of Zero: Princess Rondo (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6b910519-9b44-4d83-90fa-57bb443fdbe6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Code Geass - Lelouch of the Rebellion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6c819e0f-6053-4b96-a4b1-32ec228ae264',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hyoka',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6cd1fed7-1b3d-4c3f-a571-04e80bdfcf0a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fate/zero',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6d9b644a-a665-45ea-b94d-abaf02f65f8c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toaru Hikuushi e no Koiuta',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e289b0a-3bbb-4886-b23f-cb6f2a89aafa',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Beyond The Boundary',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6e49fcc0-8a6b-422c-8326-96d2ca31022d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Chu2byo Demo Koi Ga Shitai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7054ce78-2c58-4f43-bfe0-605682206d75',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'C³ (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '718753da-b040-4c0d-8ab1-d71fdc364de1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Berserk the Golden Age Arc  I',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '730294bf-bc71-456d-a3d5-db9d1f1b7d3d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sayonara Zetsubou Sensei',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7321392b-e01a-4878-88a2-d7ff99b483f3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Black Rock Shooter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '732883b2-bbca-4d37-8336-bbfa09fe7cb7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Yowamushi Pedal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '742b3b4f-ce6b-444b-a199-518bfa9386f7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sunday without God',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7449686e-1cca-4568-be09-7dbfa1ff4aaa',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Girl Who Leapt Through Time',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '747a7c1d-2386-4ca9-9b81-0d0c3bee2030',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Karneval',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '74c4bda4-b06a-4ce4-9806-29e3cd27aaf2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'OreGairu',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '750ddd04-d3fb-4403-ad29-2e317e2e2d5e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'FMA Brotherhood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '756b954b-7dc0-4798-8398-31005f98734a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Interstella5555',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7606a0c9-25e0-4caf-8b82-0b02e955a85c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Aoi Bungaku Series (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7615ac34-54a5-4334-a1da-c553444a0676',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sakurasou no Pet no Kanojou',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '763a9d07-8935-4b0e-8df2-72a940e0cf6b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Vampire Knight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '76555f3d-4fa5-4a35-a8cc-85e5723b1bce',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Air',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7681232e-ad93-41ff-8acf-cdc75a53e55a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hajime no Ippo: The Fighting!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '770ae4bc-e065-4d05-8e7f-8fc96b5927a7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Dragon Ball Z',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '77988d41-b55d-4421-bc2a-dda130846d81',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Psycho-Pass',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79ab4f82-1b67-428d-ae6d-4ed7fe87815b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toaru Kagaku no Railgun S',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79edcc04-ecd6-4490-8c63-e59546cf243f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Prince of Tennis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ad9939d-7524-4ec7-8762-5f849db20b04',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Jinrui Wa Suitai Shimashita',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b3f1dcb-5c75-4253-a9b3-41fd429334cc',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Eternal Family',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c111970-2932-4565-a421-4f75da7dacfb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'BECK: Mongolian Chop Squad',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c3494ff-fa09-4595-abbc-ca330626333c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Durarara!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ccd53ab-757a-4e6f-97ff-05c07860538d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Bungaku Shoujo: Memorie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7dd7e412-2b26-4b36-955c-2bb463af82e4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Date a Live!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7e332784-4c52-46ba-9d89-746c78e60229',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Blossom',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ebb0211-6558-45c3-a8de-57bd7d0ce02a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Moondrive',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f10b6dc-2a90-42ac-b744-bde0200e9c7e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Labyrinth of Flames',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f363976-d797-4851-8166-07c3f343f944',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Digimon Movie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f5d7cf4-eeeb-46b0-85ed-d0e692664e75',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Neon Genesis Evangelion (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f93dc7b-0eb7-41a3-9ddf-d9db467d5128',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Uta no Prince-sama: Maji Love 2000%',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f9ed85f-aa1f-4104-a57b-464d91e4bdb6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Lucky Star',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7fbe57ad-7e90-4fb5-b022-7c1c36af7fdf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'BTOOOM!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '80a9dd19-b64c-4d60-8273-d1d76575543b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Saint Seiya: The Lost Canvas - Meiou Shinwa (OVA)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '80ef8c27-d02d-4d1e-8998-d42186c396b9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Dragon Ball',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8125ab00-c727-4631-b6e1-c1e04777ed89',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Bleach',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '81c2c823-7788-42e7-b33b-f85e6261ec27',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tonari no Kaibutsu kun',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8210277e-dbf2-4f5a-a987-7bb57a0c6c6a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'elemental gerade',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8281f904-dade-4345-a319-25ad77f25f47',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hyouka',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '83247b9a-c3fb-4e2b-bd3f-66fe77cacfde',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Inuyasha',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8381eaaf-dc24-486b-8e8a-de68f62cf38d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'http://i47.tinypic.com/2hwl28k.png',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8487b93e-405d-4994-ac5f-f098e21174fc',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad: Afterstory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '84bbfd5f-04c9-435e-afe3-8fda3057460f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Uta no Prince-sama: Maji Love 1000%',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85b488f5-f255-4173-a12c-6a889e76c8cb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Code Geass.',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85e3fb5f-a644-460f-820e-0b153af640c5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Full metal alchemist: Brotherhood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '87f5d086-d17e-4c46-9aa1-cbd3876000f6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad: Another World, Tomoyo Chapter (OVA)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '88207961-7c85-4ba2-92d1-a91df8cf00b4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Telepathy Shoujo Ran',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '883ab653-3afe-4b82-9483-9a80027d1808',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Melancholy of Haruhi Suzumiya Season 1',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a1e5d29-aeac-4c18-a061-149c1fea840e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Idolm@ster',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8abe5a4c-a678-42fb-b3fb-accced0f1ca3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'ef - a tale of memories',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b18401d-59e0-4141-81c6-22a36bc35f54',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The World God Only Knows',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8be41485-9643-4173-8eeb-db3e6a39230a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shanghai Dragon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8cdedf2f-7615-4f38-92dc-0ebbbb4d8d70',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Suzumiya Haruhi no Yuuutsu',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8d75e2a0-14ee-404f-adee-34801cf5f70a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Monogatari',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8dee38a5-898e-4428-9824-31b31d239145',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'kakumekki valvrave',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8e50130d-552d-446f-ba91-21775e707aa5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hellsing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8e6c7422-6951-4108-8ea6-75f267ec38e1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Code Geass',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '906d3d0e-5fdb-4953-93e7-85d573b385c2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '907c1cef-d6c7-4b5c-95a1-4e5b7cd1b048',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shoujo Kakumei Utena',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90e8a16a-9bfb-47d7-857f-22afefb5cc3c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sankarea',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '91769095-4961-48c0-b9d3-ba147269ac03',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'High School DxD New',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '927a1873-3f34-4297-8710-c64df92212cd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Galilei Donna',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92be2616-8eaa-4de3-895d-13137676f203',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Melancholy of haruhi Suzumiya Movie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9339c3d6-310b-49eb-abd7-e489363b7403',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mind Game',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '934e1299-62d2-404b-96c4-832020a567fe',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Macross Frontier',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9360f771-0a57-456d-8ecc-2dfe00f34932',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Noragami',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9435d4bb-11bf-460c-ad9a-01cf587b0448',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kanon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9453d8ac-72b1-4249-9504-b953a5454143',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'One Piece',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '947b8343-fec9-41a7-bb41-af96754af714',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'My Neighbor Totoro',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '94a44ece-17e8-43d7-b11d-119b7f855489',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Campione!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '969baf7d-d065-404a-93e4-b229a6d0e979',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Panty & Stocking with Garterbelt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '96a51156-6fe5-487b-8a9e-f269241feccd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fullmetal Alchemist: Brotherhood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '985a330a-bd6f-4c76-8910-be552bab558c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tomoyo Chapter (OVA)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98865f7e-9a15-4b8d-a131-5ec36a9b4e5e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '5 centimetres per second',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98a11e5d-bf55-43f9-93f4-48e0ae0b7992',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Katekyo Hitman Reborn!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98c58a07-4a28-4195-a21d-68f54307a900',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'To Aru Majutsu no Index',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '98dceb8b-df14-4fb8-8cc9-a28568c068f2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Date A Live (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9a59146c-40d9-4b46-bc4a-4dda120b2eb7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Blood C',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9ab1f08f-c328-46ec-bf05-bc3c606ad4c7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'K-ON The Movie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9bdb2185-aaf6-4625-8d3d-a23b4f0f4723',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fullmetal Alchemist',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9c9fd8f1-d331-4adf-a7a0-da12978e51d8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Howl\'s Moving Castle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e27a607-dd86-4b94-9b4a-e403977f573e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Log Horizon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e28a57f-8870-4dd2-b37a-ec8ccecb8a56',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Magi: The Labyrinth of Magic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e463ef8-c1b6-4f94-b53b-889a9556031c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Naruto Shippuuden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9f4c2d9e-1ee7-4bdf-9183-e2a22daaa0b3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shingeki No Kyojin : Attack On Titan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9f6af1f1-8db8-4956-bfc9-f647d5152da3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Love Live! School Idol Project',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a1701360-3507-41cd-bccc-8610e16c35f0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toradora!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a217d92a-60f4-4a3c-9b75-73d14f17f773',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Diamond no Ace',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a3d7b4fe-2bc0-4d8c-ac31-adf0c0b5c0b5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Usagi Drop',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a49ad8b2-cea8-4426-830a-0cd884287a16',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fairy Tail',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a554ef45-fe54-4905-865c-37bbe7ab9825',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Redline',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a568a56d-e688-4753-be2e-e2548b2f7027',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tales of Xillia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a702a905-bf64-490b-9e21-ff7e7f526c9d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad Afterstory',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7039969-491d-4903-8e1a-25ea4ed6238c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'katte ni Kaizou',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7bcdcc0-d315-4381-99a9-1dd421159716',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The IDOLM@STER',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7d7da17-d113-4adf-8808-1e9285639a70',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Aoi Hana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8d41e83-7b3e-433d-b4bd-1c9be3ee05ee',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Baka to test to shoukanjuu',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8e92020-b8d2-40f0-8c94-1dd09bbf4684',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tron: Uprising',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8f7acc4-a2ae-4c83-9a5b-b6d0058c383f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Wolf Children Ame and Yuki',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a95cd28e-23b6-4994-944b-a07bf65a1662',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shining Hearts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aa603a88-9aff-4d28-8f3c-f4cdbbe818e9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Suisei no Gargantia',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aa88b6d5-258a-4d82-8e1f-b3730d2165d3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Animatrix',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aa9cffd9-13da-49a9-b5a5-cdf1e72d2308',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Dantalian no Shoka',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aade34cc-94e7-48a9-89ec-627ecacb60ad',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ga Rei Zero',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ac4496a4-40bf-493d-9e3b-2c5447cd6980',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Soul Eater(TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ace3ac9e-1f3e-49af-9579-36afd58225d0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'C3-CubexCursedxCurious',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'acebc51e-d8dc-4165-ad26-15d41734601b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Aiura',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad49a9b7-96d0-48e7-bde7-89f56e3ce6aa',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nisemonogatari + more',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ad4d6d3d-f098-4cfb-af40-d58a00d67a97',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Free! Iwatobi Swim Club',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ada3dd36-4f81-453e-ab1b-171e2305c23b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Pet Girl Of Sakurasou',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'adb05d27-7373-4343-9d6d-41617b28d4ac',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Money of Soul and Possibility Control',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aea3bf66-d506-461c-bc8a-0e5688351de0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Garden of Words',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af3665c6-f2a2-4d09-b4ce-b7d22c9094a3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Steins;Gate',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'af6e3c10-4734-4ee5-bc50-da6f23f3a8b1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Corpse Party Tortured Souls',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'afa8dcb9-9854-406d-a444-6c2574226f26',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Hunter x Hunter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'afea0410-20a2-4a69-92e9-dedd9e319abb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Princess Mononoke',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'affe5406-4159-4be0-8ace-954a62be48a9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Witch Craft Works',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b0a1ab6f-4779-4e72-9e9c-6713086f946d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Dragon Ball Z Kai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b0eb81f3-6949-4b7e-80a0-737f088a5c8c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nisekoi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b0f136d8-59ed-489b-adb5-9af8eb16b819',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nagi no Asakura',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b1911616-2d27-42aa-97b1-89a794ddad61',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'X/1999 TV',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b1b2a0fa-d851-44fd-b932-b8ac30a6240a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'End of Evangelion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b1d8b168-b203-46bc-bccf-b95644d808c5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Vampire Knight Guilty',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b2b8da3c-b244-4292-b800-20ccf42ee153',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'CANAAN',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b314bd62-16e8-4963-bd68-3b62f54625b8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'K-ON!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3563376-48fa-4348-b6c8-d6c6eba88c99',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Saint Onii-san',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b38624e8-4db3-467d-96e4-2f36d70dad84',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sailor Moon (MOVIEs)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b43a3384-6d9c-4097-a891-26aa7fc79953',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'code geuss',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b44fe25c-6779-4d80-bea8-a48d9c76371f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Otome Youkai Zakuro',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b48a9e83-4eb6-4b6c-9bbe-6aa3467398ad',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sakura Trick',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b4a7a56b-9966-4eac-a8a9-9596516f63d6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Freezing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5635518-5361-4234-9b87-30cb8d5aed91',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Haikyuu!!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b61b2cb5-a2f0-4ee3-b8bd-9a9f8d66e405',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Yuru Yuri',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b68eadc8-2075-4ee7-9290-8380db9b0943',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nisemonogatari (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b81b55df-9aeb-46b7-bf7a-1cd8c3100a86',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Samurai Champloo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b83f34d5-b3d8-4310-b67c-4b6f81feb9ba',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tengen Toppa Gurren Lagann (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b9417eac-83c4-46dc-92ce-56bd7ce4f907',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Perfect Blue',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b957685d-eea7-4558-a30e-097727cd8966',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gintama',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba4adf58-848d-4bd7-a640-9dde9fd6f9bd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toaru Kagaku no Railgun',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba65ba20-c807-44a8-9e19-8e5094c317c0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gyo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bb6ded62-5c2b-45bd-a8a7-be787718503d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'It’s You Guys\' Fault I’m Not Popular! (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc5edd6f-e95d-4925-bfcd-ace137828ffa',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sola',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bca955fe-280d-4d11-8b77-e89563ca9c5f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Urbance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcb0a6be-49c9-41c4-bced-28a7d3dca581',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Original 3D Animation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcb3bbbe-069a-4095-8365-a2fb74b2277d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gurren Lagann',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bdc1b85b-9218-4b3d-a624-536fefa6798d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Senki Zesshou Symphogear',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bf19bdd0-1888-4226-9269-d09cf5570cc6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'high school of the dead',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bf5dd0bc-2d55-4dbf-a8b7-3a2f96552c57',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Space Dandy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bf6240a5-16ae-4ea8-b85c-a538941d1362',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Le Portrait de petit Cossette',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c083eab6-0dd8-4f03-8909-7ec16e3cf26d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sgt. Frog',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1422921-785e-4e6b-9719-1fdc6e5aa2d1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nekomongatari',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1748ef4-0e82-4eaa-bc75-07ca6454d695',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Otome wa Boku ni Koishiteru',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1f20544-edea-4e83-93c4-e4fcb2ac3f6f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kaichou wa Maid-sama!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c2ad50d4-13b7-499b-9c86-45f5514f8c2f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Evangleion',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c35835c5-37d3-4bdd-8794-6e077d0c8782',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Heaven\'s lost Property: Angeloid of Time Movie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c39dd994-89d9-4226-8376-9004b3244604',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'fsfsff',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c44b1e27-6678-488e-85f4-e450b210abcd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gala',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c456cd26-ff56-45ad-851b-759e8d691c9c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Saint Seiya: The Lost Canvas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c45f9c42-b6ab-4d94-bfa4-344ca7c69103',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ef - the latter tale',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c4aa674c-5ce4-43bc-83fc-de49cddc54b3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Love, Chunibyo and Other Delusions,',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c4fc5603-a124-4b15-ae26-b9002bfdd7c2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Magi: The Kingdom of Magic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c53760a0-d817-44ac-a107-dc92a7d869da',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Wake Up',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c555a015-cd92-4756-9de6-dd2af3b9ac90',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ano Hi Mita Hana no Namae o Bokutachi wa Mada Shiranai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c72665ba-2e0f-4521-b65e-81dedfb31a9d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Naruto: Shippuuden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c7bf8cd1-b2eb-4773-981e-672c3753056d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Psycho Pass',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c8cfbe2f-2411-4150-8478-f73db909a1ec',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Full Moon wo Sagashite',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c91cd8d5-3030-43b2-b3e5-b2b688680361',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kami nomi zo Shiru Sekai II',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c92dad55-2a75-4da8-96d1-5e096d37a39b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Deadman Wonderland',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c955b83a-6df9-4031-8133-df894594ed8d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kokoro Connect',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c9dee52f-e390-4777-b831-2e8143705e7c',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Pretty Soldier Sailor Moon Stars',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ca0b619e-4806-4aad-9fcb-ee9d5f4e3596',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Munto',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cbb016a7-a06f-4e21-ac8f-76084459f60a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Spirited Away',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc019124-b0be-4c70-bdcc-da1fa70a11e2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ben-To',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc514c7f-6572-4e0b-8dec-b005208dad45',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Space Pirate Captain Harlock',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc52ec68-7ea3-4087-b17b-b55faa278df3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kill la Kill',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc89f68d-e8e6-48ec-b030-0092ee856739',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Loveless',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd2b7010-5b84-4db6-acfc-69e1fac12fb9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kimi ga nozomu eien',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd339d31-ab32-4991-a08a-9a7dd6998d8d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kyou Chapter (OVA)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cd52ec03-b3db-40be-9cac-527f5ccae0ec',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'hh',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cde539f1-da56-4dde-9e9d-3cfc63156d54',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Honey & Clover',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce24d257-825b-4be5-9168-ec2cde56311f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Original animation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce690de1-45d4-4c27-9d8b-76594342de70',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'and more!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce96893b-14e8-44fe-924a-3500edef4020',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shugo Chara',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cfb9194e-e4ca-40db-8305-a47a96f3ef5a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Anime: Guilty Crown',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cffa901c-b3fd-4966-b447-0ff52663fb0f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Love Lab',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd0050e96-ca81-40d3-9209-36c69e6893dc',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Rozen Maiden (2013) (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd01c939d-1985-40e0-947b-88d4bde7dcc8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Ichiban Ushiro no Daimaou',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd0f55754-a781-4182-84f1-0d2552e2ae37',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'tears to tiara...',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1a84aee-2941-41f8-972a-6b27cb920162',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shuffle!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1d80893-7a6b-47ee-aead-c97a591cbbec',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Wangan Midnight',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd2838d44-5283-45e3-bd75-bd2e7f1e3310',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sono Hanabira ni Kuchizuke o',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd2c132e7-5acc-4c35-b475-b3b3b3121620',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kemonozume',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4885c80-983f-43bf-b0b0-7a07c85f7c0b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Zetsuen no Tempest',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4b00c93-067f-45b7-9e90-9f4e9c6313af',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Karas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4f3e82d-d8ea-4211-931b-de305137f7eb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Clannad: Another World, Kyou Chapter (OVA)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd66bb3e9-4bdb-4b6d-a45a-c5ddbed2d9fb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Naruto Shippuden',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd6acbd59-8d29-452f-9f40-94dd54a70514',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Nerawareta Gakuen',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd7c684b2-4473-4314-820e-499d2018de39',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shingeki no Kyojin/ Attack on titan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd8014e5f-0bf4-4bb3-b908-dfa7d3083d0e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'black cat',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd8855594-ae95-46c6-8fac-a8ba83408232',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Seitokai no ichizon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd90609b1-05b3-40d7-97cd-9256fc4c006a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Melancholy of Haruhi Suzumiya',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd912bea8-f940-483c-b356-ff0e5db8d7a4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'NINkzPGJuOwNr',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd9f3e25c-1914-407b-ab69-855299ad13e9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Durarara!!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da38651c-a3ae-4366-9ed2-90d6baa40345',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'White Album 2',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da7db28d-5622-49ad-9ee8-7080aa10a744',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Card captors Sakura',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da917537-4b9f-4ac3-a5ee-1b3be50e7dd2',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Honey & Clover II',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'db0010e1-0d7a-4dc3-9333-bf7e6ca88192',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Michiko & Hatchin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'db1f6c7e-9575-4aad-9438-945a712b3ea0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shinryaku! Ika Musume (',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'db52fe6d-31c5-445e-8657-f5d4bd88b532',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Girls!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'db61dd48-51ad-439d-8670-e4bc3a6adbc9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'C - The Money of Soul and Possibility Control',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc7726e0-d2d8-468c-9dad-0070a2d26fcf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Love',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc897d0c-283c-436e-9501-e667eaa14690',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'ah my goddess',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dcfacfec-e3ba-4abe-ae5f-953e3fb62614',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'mermaid melody',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dd8c4148-642b-4007-8c65-5bc21ad67771',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Maken-Ki! Battling Venus (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'de6dbd32-6b72-4a52-a75a-3ad85803f3ad',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Chuunbyou Demo Koi Ga Shitai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df779c19-cc9d-41f6-8d16-58d843cc65c5',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Shingeki no Kyojin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0524f01-049e-4056-be1d-b99d8941ae40',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'A-Channel The Animation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e09f474b-338b-446c-a997-d8bdc0736ed4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Disappearance Of Haruhi Suzumiya',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0fe8356-9009-443d-a862-3fa6d6f9387d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Various (It wont let me post the full list here since its 50+ series)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e11c5162-1c95-4d1f-afa6-eb9f1ba69a65',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => '(+4)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e195a50a-1ddd-4bb4-88e6-0ed6ada307d6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Eve no Jikan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e19c6d23-3339-45a4-a52c-5ecb0e277d32',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Free!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e1b4ae77-7d37-4d6f-849e-0464c95bdc5a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fate/Extra CCC',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3f1d13f-d13a-4da9-ade3-5a1c8f764c3b',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Serial experiments Lain',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e4408cf1-fa13-4096-8d4e-6fd87782104e',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Toki wo Kakeru Shoujo',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e47d78da-5d39-48f3-8559-6b74f2a2aa05',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tengen Toppa Gurren Lagan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e4ad4a28-f6f7-4ee9-84c6-2eade3814013',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'CardCaptor Sakura',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e4ec1f51-a49f-47b1-ae3f-da8bb5a9a975',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Jojo\'s Bizarre Adventure',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5695add-3069-4763-a7b5-5331af079162',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Pokemon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e575f02c-f5ea-4980-b161-18649795d837',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'High School DxD',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e593153b-0fad-4880-9796-b16d48949860',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Captain Earth',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5fff584-3a2d-4f73-9459-7975c2b61ad9',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Idolmaster',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e668cd9c-0dac-42fd-b540-0e432e75aba3',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Punks Jump Up Mr Overtime',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6b50e36-91ef-44e6-9f10-94278b619b9a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Haruhi Suzumiya',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7c5c91b-4042-4322-ae0c-36d23d6c0ae4',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Lost Canvas',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e988ac4f-958b-4445-a2ed-40bd0f2fb248',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'the Children who Chase Lost Voices',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eaafeb3f-f80c-4529-ade1-f6301640b38a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tsubasa Chronicles',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ec0f2ece-7746-41bd-b94a-b676eb9f8315',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'TIkxvguirQDSXGbbxWB',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ed1b0408-42f7-4a5d-8431-e1c2481452ea',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Another',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'edb0492e-756c-487b-8c10-348ccdcdad54',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Tengen Toppa Gurren Lagann',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'edd4c7d2-20cd-4c12-be95-031cc1035e43',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Yu Yu Hakusho',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ee0148f6-4c46-497d-95bd-8fad3db3dd7a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Fate/Zero; Fate/Stay Night & Unlimited Blade Works',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef52c132-ad48-40e7-abd3-06578309e5f6',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Blood-C: The Last Dark (Movie)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef89f5bb-7227-47bb-9bb6-ebecae1dce18',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'The Garden of Words',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'efc14d13-031f-4673-bfa8-a4535f27fa64',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'City Hunter (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f077e1bc-9929-49ac-a9d0-b80586a36853',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mekakunin de Shinkoukei',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f0e4c676-391f-42ae-bf1f-f6221afa48ba',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kami nomi zo Shiru Sekai',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f10234b5-8f38-43d6-8396-9e87e7d3cd30',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kara No Kyoukai - The Garden Of Sinners (Movie)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f148e6b9-50c9-409c-a148-37caa93c8660',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'ef',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f17a175d-6b90-457f-8665-5602dc18cb39',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Anime:Guilty Crown',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f18e086b-c0e4-45d2-9394-ca5a776fe05f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Macross Frontier MUSIC CLIP Collection',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1ca594b-1253-4011-812e-b2848948e1dd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kannagi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f3695252-a4ab-41fb-8fd1-d31e97b32f0f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'shakugan no shana',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f381f5b2-5409-45c0-a580-cdbc27e46da1',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'pretear',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f39a9569-84bd-4575-a9c5-c6b7da925efd',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'K Project',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f3a1c5d6-b5f6-4455-9dee-a5437136959a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Naruto',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f5542bea-bd70-441d-b01f-bff0278285de',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Macademi Wasshoi!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f5a7a078-f331-451d-862d-7a3efe7a65f7',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'To Aru Kagaku No Railgun',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f60ccc47-cb95-4b92-919f-aa405207faf0',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'AKB48',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f6573c65-97e5-40af-8eee-b684d0cdbe89',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'yyyuih@iknvcr.com',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f78d7bfa-9da5-417c-9701-1445b9956074',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Zero no Tsukaima',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f8673042-0fc5-44a7-901b-3d9a91a0821a',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mahouka',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f8ca4585-f6ba-4134-aca4-288f477d7526',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Beck',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f8f048ac-dc18-4751-9b30-7dc31f54c10f',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Durarara!!!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f8fa08f4-4e34-4ffc-afbc-a6c88351f1dc',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Casshern Sins',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f922510a-5ffc-4e02-8c01-a6529b9e4106',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'ffffs',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f98a8762-b06d-4a40-afba-ef71c1937f46',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Mawaru Penguindrum',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa1c8ef1-f3b9-4a81-93c0-b13ab6178c5d',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'katekyo hitman reborn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa39c328-3fd5-4516-941d-060f8e6152eb',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kung Fu Love',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fa5ff334-98dc-4d3c-8bed-cbee0d1249e8',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Sword Art Online',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fbc03b91-eae3-44f8-84f3-9201f87196ad',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'No.6',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fbd62ad0-8ba5-4335-b879-dbc73c7f93bf',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kamisama no Inai Nichiyoubi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fbd8d0a8-3101-42d5-931a-6e936d3bfc06',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Last Exile',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc0ee47b-79ab-4bfe-b610-0cc753ae7d83',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Puella Magi Madoka  Magica',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc2fcb9e-c144-492c-9f75-b003b409aa92',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Dusk Maiden Of Amnesia (TV)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc3a4166-8834-47ff-94d8-8b45613df9df',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Gosick',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fc8ba1b1-f834-4166-8909-84be5751ba43',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Little Busters!',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fd94102d-fc8d-461e-8dfd-12308cbefd76',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Bakemonogatari',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fdb3d677-7dea-40d4-b7a5-6d968664cc87',
    'vocabulary_machine_name' => 'series',
  );
  $terms[] = array(
    'name' => 'Kyousougiga',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fe0d5a73-2cb4-4325-bb42-97dda6ba0d9d',
    'vocabulary_machine_name' => 'series',
  );
  return $terms;
}
