<?php
/**
 * @file
 * Code for the AMV Base feature.
 */

include_once 'amv_base.features.inc';

function amv_base_form_amv_node_form_alter(&$form, &$form_state, $form_id) {
	// drupal_set_message('<pre>' . print_r($form, 1) . '</pre>');

	drupal_set_title("2013 SMASH! AMV Competition Online Submission Form");

	$form['intro'] = array(
		'#weight' => -999,
		'#markup' => '<p>' . t("This is the form for online submissions for the 2013 SMASH! AMV Competition. Please make sure you fill in all the necessary details so we know more about you and your AMVs, as these will help us later on with organisation and judging.") . '</p>',
	);

	$form['title']['#title'] = t('AMV Title');
	$form['title']['#description'] = t('Please enter the title of your AMV.');
}
